/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDashboard_layoutRouteImport } from './routes/_authed/dashboard_._layout'
import { Route as AuthedDashboard_layoutTransactionsRouteImport } from './routes/_authed/dashboard_._layout.transactions'
import { Route as AuthedDashboard_layoutTransactionsNewRouteImport } from './routes/_authed/dashboard_._layout.transactions_.new'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboard_layoutRoute = AuthedDashboard_layoutRouteImport.update({
  id: '/dashboard_/_layout',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboard_layoutTransactionsRoute =
  AuthedDashboard_layoutTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthedDashboard_layoutRoute,
  } as any)
const AuthedDashboard_layoutTransactionsNewRoute =
  AuthedDashboard_layoutTransactionsNewRouteImport.update({
    id: '/transactions_/new',
    path: '/transactions/new',
    getParentRoute: () => AuthedDashboard_layoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboard_layoutRouteWithChildren
  '/dashboard/transactions': typeof AuthedDashboard_layoutTransactionsRoute
  '/dashboard/transactions/new': typeof AuthedDashboard_layoutTransactionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboard_layoutRouteWithChildren
  '/dashboard/transactions': typeof AuthedDashboard_layoutTransactionsRoute
  '/dashboard/transactions/new': typeof AuthedDashboard_layoutTransactionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/dashboard_/_layout': typeof AuthedDashboard_layoutRouteWithChildren
  '/_authed/dashboard_/_layout/transactions': typeof AuthedDashboard_layoutTransactionsRoute
  '/_authed/dashboard_/_layout/transactions_/new': typeof AuthedDashboard_layoutTransactionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/transactions'
    | '/dashboard/transactions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/transactions'
    | '/dashboard/transactions/new'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/_authed/dashboard_/_layout'
    | '/_authed/dashboard_/_layout/transactions'
    | '/_authed/dashboard_/_layout/transactions_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard_/_layout': {
      id: '/_authed/dashboard_/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboard_layoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard_/_layout/transactions': {
      id: '/_authed/dashboard_/_layout/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof AuthedDashboard_layoutTransactionsRouteImport
      parentRoute: typeof AuthedDashboard_layoutRoute
    }
    '/_authed/dashboard_/_layout/transactions_/new': {
      id: '/_authed/dashboard_/_layout/transactions_/new'
      path: '/transactions/new'
      fullPath: '/dashboard/transactions/new'
      preLoaderRoute: typeof AuthedDashboard_layoutTransactionsNewRouteImport
      parentRoute: typeof AuthedDashboard_layoutRoute
    }
  }
}

interface AuthedDashboard_layoutRouteChildren {
  AuthedDashboard_layoutTransactionsRoute: typeof AuthedDashboard_layoutTransactionsRoute
  AuthedDashboard_layoutTransactionsNewRoute: typeof AuthedDashboard_layoutTransactionsNewRoute
}

const AuthedDashboard_layoutRouteChildren: AuthedDashboard_layoutRouteChildren =
  {
    AuthedDashboard_layoutTransactionsRoute:
      AuthedDashboard_layoutTransactionsRoute,
    AuthedDashboard_layoutTransactionsNewRoute:
      AuthedDashboard_layoutTransactionsNewRoute,
  }

const AuthedDashboard_layoutRouteWithChildren =
  AuthedDashboard_layoutRoute._addFileChildren(
    AuthedDashboard_layoutRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDashboard_layoutRoute: typeof AuthedDashboard_layoutRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDashboard_layoutRoute: AuthedDashboard_layoutRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
